/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "eip712.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SimpleMessage, SimpleMessage, AUTO)

PB_BIND(LinkedList, LinkedList, AUTO)

PB_BIND(KAryTree, KAryTree, AUTO)

PB_BIND(TypedDataStruct, TypedDataStruct, AUTO)

PB_BIND(TypedDataStruct_TypedDataNode, TypedDataStruct_TypedDataNode, AUTO)

PB_BIND(MessageData, MessageData, AUTO)
