/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "simple.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LinkedList, LinkedList, AUTO)

PB_BIND(TypedDataStruct, TypedDataStruct, AUTO)

PB_BIND(TypedDataStruct_Eip712StructMember, TypedDataStruct_Eip712StructMember, AUTO)

PB_BIND(TypedDataStruct_Eip712FieldType, TypedDataStruct_Eip712FieldType, AUTO)

PB_BIND(MessageData, MessageData, AUTO)
